name: Pull Request Check
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./example-nextjs-app

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nextjs-version: [ 12, 13, 14 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: yarn --frozen-lockfile
        working-directory: ./example-nextjs-app
      - run: yarn add next@${{ matrix.nextjs-version }}
        working-directory: ./example-nextjs-app
      - run: yarn run lint
        working-directory: ./example-nextjs-app
      - run: yarn build
        working-directory: ./example-nextjs-app
